FROM golang:1.8

RUN mkdir -p /go/src/app
WORKDIR /go/src/app
ADD *.go /go/src/app/
ADD vendor /go/src/app/vendor
RUN go-wrapper download
RUN go-wrapper install
ARG version
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o feeder -ldflags "-X main.version=$version" 
CMD cp feeder /dest/